language: ruby
rvm:
- 2.3.0
bundler_args: "--without development production"
before_install:
- gem update --system
- gem --version
script:
- bundle exec rake db:drop db:create db:migrate
- bundle exec rspec spec
